services:
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: source/frontend
      dockerfile: ./Dockerfile   
    ports:
      - 3000:3000
    depends_on:
      - backend  
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5001
      - NODE_ENV=production
    networks:
      - app-network      

  

  backend:
    image: backend
    container_name: backend
    build:
      context: source/backend
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
    restart: always
    networks:
      - app-network 
    environment:   
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
      - FLASK_DEBUG=0
    depends_on:
      - db   


  db: 
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./source/backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    ports:
      - 5432:5432 
    
volumes:
  postgres_data: {}

networks:
  app-network:
    driver: bridge
